server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html; # Ruta estándar en el contenedor de Nginx
        index index.html;
        try_files $uri $uri/ /index.html; # El $uri/ ayuda a reconocer carpetas
    }

    # Corregido el espacio en el nombre del archivo 50x
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}